// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACZZxScuRWqV7TKnBFx-PkO_1PY0FL0cA',
    appId: '1:1025259963721:web:49ca6f61bffa346ebb0698',
    messagingSenderId: '1025259963721',
    projectId: 'demoflutter-f3cc2',
    authDomain: 'demoflutter-f3cc2.firebaseapp.com',
    storageBucket: 'demoflutter-f3cc2.appspot.com',
    measurementId: 'G-R9GVD38N5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAds4NxzvBtnOzhjgnIl6mtAuciS57kA_Q',
    appId: '1:1025259963721:android:17df8372735acb3fbb0698',
    messagingSenderId: '1025259963721',
    projectId: 'demoflutter-f3cc2',
    storageBucket: 'demoflutter-f3cc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVp5bvNmWavaaXoPwy109ikK5PPVoyCwQ',
    appId: '1:1025259963721:ios:3a1eb7172eac7df6bb0698',
    messagingSenderId: '1025259963721',
    projectId: 'demoflutter-f3cc2',
    storageBucket: 'demoflutter-f3cc2.appspot.com',
    iosBundleId: 'com.example.demoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVp5bvNmWavaaXoPwy109ikK5PPVoyCwQ',
    appId: '1:1025259963721:ios:aaeb799860b6067fbb0698',
    messagingSenderId: '1025259963721',
    projectId: 'demoflutter-f3cc2',
    storageBucket: 'demoflutter-f3cc2.appspot.com',
    iosBundleId: 'com.example.demoFlutter.RunnerTests',
  );
}
